#!/usr/bin/env bash
# script that will display information about subdomains.


function func () {
    if [ $# -eq 2 ]; then
        DOMAIN="$1"
        SUB_DOMAIN="$2"
        records=("A" "CNAME" "MX" "TXT" "NS" "SOA")
        
        for record_type in "${records[@]}"; do
            dig +short "$SUB_DOMAIN.$DOMAIN" "$record_type" | awk -v sub_dom="$SUB_DOMAIN" -v record_type="$record_type" '{ print "The subdomain "sub_dom" is a "record_type" record and points to " $0; }'
        done
    else
        DOMAIN="$1"
        SUB_DOMAINS=("www" "lb-01" "web-01" "web-02")
        records=("A" "CNAME" "MX" "TXT" "NS" "SOA")

        for sub_dom in "${SUB_DOMAINS[@]}"; do
            for record_type in "${records[@]}"; do
                dig +short "$sub_dom.$DOMAIN" "$record_type" | awk -v sub_dom="$sub_dom" -v record_type="$record_type" '{ print "The subdomain "sub_dom" is a "record_type" record and points to " $0; }'
            done
        done
    fi
}

if [ $# -eq 2 ]; then
    func "$1" "$2"
else
    func "$1"
fi
