#!/usr/bin/env bash
# script that will display information about urls in ubuntu 16.04

func ()
{
	if [ $# -eq 2 ]
	then
		DOMAIN=$1
		SUBDOMAIN=$2
		dig "$SUBDOMAIN.$DOMAIN" +noall +answer | tail -n 1 | awk -v SUB=$SUBDOMAIN '{ print "The subdomain "SUB" is a "$4" record and points to "$NF}'
	else
		DOMAIN=$1

		dig "www.$DOMAIN" +noall +answer | tail -n 1 | awk '{ print "The subdomain www is a "$4" record and points to "$NF}'

		dig "lb-01.$DOMAIN" +noall +answer | tail -n 1 | awk '{ print "The subdomain lb-01 is a "$4" record and points to "$NF}'

		dig "web-01.$DOMAIN" +noall +answer | tail -n 1 | awk '{ print "The subdomain web-01 is a "$4" record and points to "$NF}'

		dig "web-02.$DOMAIN" +noall +answer | tail -n 1 | awk '{ print "The subdomain web-02 is a "$4" record and points to "$NF}'
	fi
}

if [ $# -eq 2 ]; then
    func "$1" "$2"
else
    func "$1"
fi
