#!/usr/bin/env bash
# Install nginx on your web-01
sudo apt update;
sudo apt install -y nginx

# querying Nginx at its root '/' return a page that contains Hello World!
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

#restart Nginx
sudo service nginx restart
