#!/usr/bin/env bash
# Install nginx on your web-01
sudo apt update;
sudo apt install -y nginx

# querying Nginx at its root '/' return a page that contains Hello World!
sudo echo 'Hello World!' > /var/www/html/index.html

#restart Nginx
service nginx restart
