#!/usr/bin/env bash
# script to Configure your Nginx server so that /redirect_me is redirecting to another page.
sudo su;
sudo apt-get -y update;
sudo apt-get -y install nginx;

echo "Hello World!" > /var/www/html/index.nginx-debian.html;
sudo service nginx start;

new_string = "location /redirect_me {
                return 301 http://www.youtube.com/watch?v=QH2-TGUlwu4;
        }"

sed -i "s/# pass PHP scripts to FastCGI server/$new_string/" /etc/nginx/sites-available/default;
