#!/usr/bin/env bash
# Script to configure your Nginx server to redirect /redirect_me to another page.

# Use sudo for specific commands instead.
sudo su;

# Update package lists and install Nginx.
sudo apt-get -y update;
sudo apt-get -y install nginx;

# Create a simple index page.
echo "Hello World!" > /var/www/html/index.nginx-debian.html;

# Start the Nginx service.
sudo ufw allow 'Nginx HTTP';
sudo sed -i "24i\    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }" /etc/nginx/sites-available/default;
sudo sed -i "28i\    location /xyz {\n        return 404 "Ceci n\'est pas une page";\n    }" /etc/nginx/sites-available/default;

sudo service nginx start;
sudo nginx -s reload;
