#!/usr/bin/env bash
# script to Configure Nginx server so that /redirect_me is redirecting to another page.
# Use sudo for specific commands instead.

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
echo "Ceci n'est pas une page!" | sudo tee /var/www/html/custom_404.html > /dev/null

sudo ufw allow 'Nginx HTTP'


#string_to_replace="        #location ~ \.php$ {
#        #       include snippets/fastcgi-php.conf;
#        #
#        #       # With php-fpm (or other unix sockets):
#        #       fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;"
#
#new_string="        location /redirect_me {
#                return 301 https://youtu.be/DdWxCVYAOCk?si=atOWK-lu9lCY5E0s;
#        }
#"

sudo sed -i "24i\    location /redirect_me {\n        return 301 https://youtu.be/DdWxCVYAOCk?si=yydqdPnvL3iMMdh3;\n    }" /etc/nginx/sites-available/default

err_str="	error_page 404 /custom_404.html{
			location = /custom_404.html {
				root /usr/share/nginx/html;	
				internal; 
      }
	}"


sudo sed -i "45i\\$err_str" /etc/nginx/sites-available/default

sudo service nginx start
sudo nginx -s reload
