#!/usr/bin/env bash
# script to Configure Nginx server so that /redirect_me is redirecting to another page.
# Use sudo for specific commands instead.
sudo apt-get -y update
sudo apt-get -y install nginx

sudo service nginx start


echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null


sudo ufw allow 'Nginx HTTP'

sudo sed -i '58i\\terror_page 404 /custom_404.html;' /etc/nginx/sites-available/default

sudo sed -i '/.*server_name _/a \\tadd_header X-Served-By \$hostname;' /etc/nginx/sites-available/default


sudo service nginx restart;
