#!/usr/bin/env bash
# load balancer configuration

# Install and configure HAproxy on load balancing lb-01 server.
sudo apt-get -y update

sudo apt-get -y install haproxy


echo "

frontend myfrontend
  bind *:80
  timeout client 60s
  mode http
  default_backend allservers

backend allservers
  timeout connect 10s 
  timeout server 10s 
  mode http
  server 338638-web-01 100.25.22.31
  server 338638-web-02 100.25.162.125

" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart;
