#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
i=0
while [ $i -ne 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"

	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best school"
	fi
	i=$((i+1))
done
	
