#!/usr/bin/env bash
# configures an Ubuntu server with: localhost resolves to 127.0.0.2, facebook.com resolves to 8.8.8.8.
# checker is running on Docker, so make sure to read https://intranet.alxswe.com/rltoken/XSXhQPoDu3QecXs3j9XgPQ
cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
