#!/usr/bin/env bash
# make Nginx run by the "nginx" user.
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf

# nginx listening on all active IPs on port 8080
sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default 
sudo sed -i 's#listen \[::\]:80 default_server ipv6only=on;#listen [::]:8080 default_server ipv6only=on;#' /etc/nginx/sites-available/default

# apache from listening on port 8080
sudo service apache2 stop

pkill apache2 
chmod a+r /etc/nginx/nginx.conf
sudo -u nginx service nginx start
