#!/usr/bin/env bash
# make Nginx run by the "nginx" user.
sudo sed -i '1s/#user www-data/user nginx/' /etc/nginx/nginx.conf

# nginx listening on all active IPs on port 8080
chmod a+r /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
# apache from listening on port 8080
sudo service apache2 stop

pkill apache2 
sudo -u nginx service nginx restart
