#!/usr/bin/env bash
# make Nginx run by the "nginx" user.
sudo sed -i '1s/.*/user nginx/' /etc/nginx/nginx.conf
chmod 444 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache2 
sudo -u nginx service nginx restart
